version: "3.9"
services:
  aspnetapp:
    environment:
    - SOME_KEY= HOLA MUNDO!
    build: 
        context: .
        dockerfile: Dockerfile.nanoserver-x64
    ports:
      - "8080:80"
    image: 'ignaciocolmenares/aspnetapp:nanoserver'
    container_name: aspnetapp
    restart: always

#docker compose -f .\compose-nanoserver.yaml  build
#docker compose -f .\compose-nanoserver.yaml  up -d  --no-build --remove-orphans
